// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzU7-0P_iOCMyixHB23w5OF83hDyTI30',
    appId: '1:291276455080:web:93d94a38b18304076e969d',
    messagingSenderId: '291276455080',
    projectId: 'sanber-login',
    authDomain: 'sanber-login.firebaseapp.com',
    storageBucket: 'sanber-login.firebasestorage.app',
    measurementId: 'G-S52741YBVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL5hkCrbfwfRNKqwejjer-oSEgp0RzF-c',
    appId: '1:291276455080:android:7976a7fd90c145b06e969d',
    messagingSenderId: '291276455080',
    projectId: 'sanber-login',
    storageBucket: 'sanber-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc0HBn1GXE5xznq9YuI7g-vycr2IoSL6E',
    appId: '1:291276455080:ios:2d28552d93ad28486e969d',
    messagingSenderId: '291276455080',
    projectId: 'sanber-login',
    storageBucket: 'sanber-login.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc0HBn1GXE5xznq9YuI7g-vycr2IoSL6E',
    appId: '1:291276455080:ios:2d28552d93ad28486e969d',
    messagingSenderId: '291276455080',
    projectId: 'sanber-login',
    storageBucket: 'sanber-login.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXzU7-0P_iOCMyixHB23w5OF83hDyTI30',
    appId: '1:291276455080:web:1a0fb0aff7a0e1586e969d',
    messagingSenderId: '291276455080',
    projectId: 'sanber-login',
    authDomain: 'sanber-login.firebaseapp.com',
    storageBucket: 'sanber-login.firebasestorage.app',
    measurementId: 'G-ZT2Z52XTT5',
  );
}
