// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTuhTeo9A_9nhAy9dhkHUJv4o_6bXuew',
    appId: '1:213347808814:web:1fa49e61d16f2ce21011bf',
    messagingSenderId: '213347808814',
    projectId: 'route-management-demo',
    authDomain: 'route-management-demo.firebaseapp.com',
    storageBucket: 'route-management-demo.firebasestorage.app',
    measurementId: 'G-9BXHYLD6M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHSccBkLNqTk3WhHnioANtt6J6JYYjqKU',
    appId: '1:213347808814:android:c8ce8461696614d61011bf',
    messagingSenderId: '213347808814',
    projectId: 'route-management-demo',
    storageBucket: 'route-management-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0NYPhEtmUPTzPOPQcOIyEEEu47vF_jJE',
    appId: '1:213347808814:ios:24d36e226508e53a1011bf',
    messagingSenderId: '213347808814',
    projectId: 'route-management-demo',
    storageBucket: 'route-management-demo.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0NYPhEtmUPTzPOPQcOIyEEEu47vF_jJE',
    appId: '1:213347808814:ios:24d36e226508e53a1011bf',
    messagingSenderId: '213347808814',
    projectId: 'route-management-demo',
    storageBucket: 'route-management-demo.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZTuhTeo9A_9nhAy9dhkHUJv4o_6bXuew',
    appId: '1:213347808814:web:ee4c61484ce3d4841011bf',
    messagingSenderId: '213347808814',
    projectId: 'route-management-demo',
    authDomain: 'route-management-demo.firebaseapp.com',
    storageBucket: 'route-management-demo.firebasestorage.app',
    measurementId: 'G-R4B1X4DZ5K',
  );
}
